export enum AccionesBitacora {
  CREAR_PLAN_SUSCRIPCION = 'CREAR_PLAN_SUSCRIPCION',
  CREAR_SUSCRIPCION = 'CREAR_SUSCRIPCION',
  CREATE_ADMIN = 'CREATE_ADMIN',
  CREATE_USER = 'CREATE_USER',
  DELETE_ADMIN = 'DELETE_ADMIN',
  DELETE_USER = 'DELETE_USER',
  ERROR = 'ERROR',
  GET_USUARIOS = 'GET_USUARIOS',
  LOGIN = 'LOGIN',
  RECHAZAR_SUSCRIPCION = 'RECHAZAR_SUSCRIPCION',
  UPDATE_ADMIN = 'UPDATE_ADMIN',
  UPDATE_PLAN_SUSCRIPCION = 'UPDATE_PLAN_SUSCRIPCION',
  UPDATE_USER = 'UPDATE_USER',
  VALIDAR_SUSCRIPCION = 'VALIDAR_SUSCRIPCION',
  VENCIADA_SUSCRIPCION = 'VENCIADA_SUSCRIPCION',
  VIEW = 'VIEW'
}

export enum EstatusSuscripcion {
  PENDIENTE = 'PENDIENTE',
  RECHAZADA = 'RECHAZADA',
  VALIDADO = 'VALIDADO',
  VENCIDO = 'VENCIDO'
}

export enum NivelAcademico {
  LICENCIADO = 'LICENCIADO',
  TSU = 'TSU'
}

export enum Rol {
  ADMINISTRADOR = 'ADMINISTRADOR',
  AGREMIADO_INSOLVENTE = 'AGREMIADO_INSOLVENTE',
  AGREMIADO_SOLVENTE = 'AGREMIADO_SOLVENTE',
  ESTUDIANTE = 'ESTUDIANTE',
  PROFESOR = 'PROFESOR',
  SUPER_USUARIO = 'SUPER_USUARIO',
  VISITANTE = 'VISITANTE'
}

export enum TipoAutoridad {
  PRESIDENTE = 'PRESIDENTE',
  VICEPRESIDENTE = 'VICEPRESIDENTE'
}

export enum TipoEvento {
  CONGRESO = 'CONGRESO',
  DIPLOMADO = 'DIPLOMADO',
  TALLER = 'TALLER'
}

export enum TipoSuscripcion {
  AGREMIADO = 'AGREMIADO',
  ESTUDIANTE = 'ESTUDIANTE',
  PROFESOR = 'PROFESOR'
}
