export enum AccionesBitacora {
  CREAR_EVENTO = 'CREAR_EVENTO',
  CREAR_PLAN_SUSCRIPCION = 'CREAR_PLAN_SUSCRIPCION',
  CREAR_SUSCRIPCION = 'CREAR_SUSCRIPCION',
  CREATE_ADMIN = 'CREATE_ADMIN',
  CREATE_USER = 'CREATE_USER',
  DELETE_ADMIN = 'DELETE_ADMIN',
  DELETE_USER = 'DELETE_USER',
  ERROR = 'ERROR',
  GENERACION_CARNET = 'GENERACION_CARNET',
  GENERACION_CARNET_PONENTE = 'GENERACION_CARNET_PONENTE',
  GENERACION_CERTIFICADO_CONGRESO = 'GENERACION_CERTIFICADO_CONGRESO',
  GENERACION_CERTIFICADO_DIPLOMADO = 'GENERACION_CERTIFICADO_DIPLOMADO',
  GENERACION_CERTIFICADO_TALLER = 'GENERACION_CERTIFICADO_TALLER',
  GENERACION_COMPROBANTE_PAGO = 'GENERACION_COMPROBANTE_PAGO',
  GENERACION_SOLVENCIA_PAGO = 'GENERACION_SOLVENCIA_PAGO',
  GET_USUARIOS = 'GET_USUARIOS',
  LOGIN = 'LOGIN',
  RECHAZAR_SUSCRIPCION = 'RECHAZAR_SUSCRIPCION',
  UPDATE_ADMIN = 'UPDATE_ADMIN',
  UPDATE_EVENTO = 'UPDATE_EVENTO',
  UPDATE_PLAN_SUSCRIPCION = 'UPDATE_PLAN_SUSCRIPCION',
  UPDATE_USER = 'UPDATE_USER',
  USUARIO_AGG_AL_EVENTO = 'USUARIO_AGG_AL_EVENTO',
  VALIDAR_SUSCRIPCION = 'VALIDAR_SUSCRIPCION',
  VENCIADA_SUSCRIPCION = 'VENCIADA_SUSCRIPCION',
  VIEW = 'VIEW'
}

export enum EstatusPagoEvento {
  ASISTIO = 'ASISTIO',
  NO_ASISTIO = 'NO_ASISTIO',
  PAGADO = 'PAGADO',
  PENDIENTE = 'PENDIENTE',
  RECHAZADO = 'RECHAZADO'
}

export enum EstatusSuscripcion {
  PENDIENTE = 'PENDIENTE',
  RECHAZADA = 'RECHAZADA',
  VALIDADO = 'VALIDADO',
  VENCIDO = 'VENCIDO'
}

export enum NivelAcademico {
  LICENCIADO = 'LICENCIADO',
  NO_ASIGNADO = 'NO_ASIGNADO',
  TSU = 'TSU'
}

export enum Rol {
  ADMINISTRADOR = 'ADMINISTRADOR',
  AGREMIADO_INSOLVENTE = 'AGREMIADO_INSOLVENTE',
  AGREMIADO_SOLVENTE = 'AGREMIADO_SOLVENTE',
  ESTUDIANTE = 'ESTUDIANTE',
  PROFESOR = 'PROFESOR',
  SUPER_USUARIO = 'SUPER_USUARIO',
  VISITANTE = 'VISITANTE'
}

export enum TipoAutoridad {
  PRESIDENTE = 'PRESIDENTE',
  SECRETARIO_ACADEMICO = 'SECRETARIO_ACADEMICO',
  SECRETARIO_ACTAS = 'SECRETARIO_ACTAS',
  SECRETARIO_EVENTOS = 'SECRETARIO_EVENTOS',
  SECRETARIO_FINANSAS = 'SECRETARIO_FINANSAS',
  SECRETARIO_GENERAL = 'SECRETARIO_GENERAL',
  SECRETARIO_PRENSA = 'SECRETARIO_PRENSA',
  VICEPRESIDENTE = 'VICEPRESIDENTE'
}

export enum TipoDeDocumento {
  CARNET = 'CARNET',
  CARNET_PONENTE = 'CARNET_PONENTE',
  CERTIFICADO_CONGRESO = 'CERTIFICADO_CONGRESO',
  CERTIFICADO_DIPLOMADO = 'CERTIFICADO_DIPLOMADO',
  CERTIFICADO_TALLER = 'CERTIFICADO_TALLER',
  COMPROBANTE_PAGO = 'COMPROBANTE_PAGO',
  SOLVENCIA_PAGO = 'SOLVENCIA_PAGO'
}

export enum TipoEvento {
  CONGRESO = 'CONGRESO',
  DIPLOMADO = 'DIPLOMADO',
  TALLER = 'TALLER'
}

export enum TipoSuscripcion {
  AGREMIADO = 'AGREMIADO',
  AGREMIADO_LICENCIADO = 'AGREMIADO_LICENCIADO',
  AGREMIADO_TSU = 'AGREMIADO_TSU',
  ESTUDIANTE = 'ESTUDIANTE',
  PROFESOR = 'PROFESOR',
  VISITANTE = 'VISITANTE'
}

export enum VigenciaEvento {
  CANCELADO = 'CANCELADO',
  CONCLUIDO = 'CONCLUIDO',
  VIGENTE = 'VIGENTE'
}
