import GET_SUSCRIPCIONES_EVENTO from "./GET_SUSCRIPCIONES_EVENTO";
import UPDATE_SUSCRIPCION_EVENTO_ESTATUS from "./UPDATE_SUSCRIPCION_EVENTO_ESTATUS";

export {
    GET_SUSCRIPCIONES_EVENTO,
    UPDATE_SUSCRIPCION_EVENTO_ESTATUS
};  
